apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
       containers:
         - name: medicure
           image: ajaymaverick/project3medicure:latest
           ports:
             - containerPort: 8082
               name: http-web-app-01
